version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 80:5000
    volumes:
     - ./:/app
    links:
      - db:db
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      PYTHONUNBUFFERED: 1
      HOST: 0.0.0.0

  db:
    image: k0st/alpine-mariadb:latest
    volumes:
      - /var/lib/mysql
